// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaHangBuffetPBL3.DataAccess.Data;

#nullable disable

namespace NhaHangBuffetPBL3.DataAccess.Migrations
{
    [DbContext(typeof(NhaHangBuffetContext))]
    partial class NhaHangBuffetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatingId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId");

                    b.HasIndex("SeatingId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Cart", b =>
                {
                    b.Property<int>("SeaatingId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOrder")
                        .HasColumnType("datetime2");

                    b.HasKey("SeaatingId", "FoodId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodName = "Thăn bò nướng",
                            Image_Url = "https://www.slenderkitchen.com/sites/default/files/styles/gsd-1x1/public/recipe_images/grilled-sirloin-chimichurri.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 2,
                            FoodName = "Ba chỉ nướng",
                            Image_Url = "https://chedoan.com/wp-content/uploads/2023/04/cach-uop-thit-ba-chi-nuong-4.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 3,
                            FoodName = "Cánh gà nướng",
                            Image_Url = "https://poshjournal.com/wp-content/uploads/2021/02/thai-bbq-chicken-wings-8.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 4,
                            FoodName = "Chân gà nướng",
                            Image_Url = "https://nghebep.com/wp-content/uploads/2018/07/chan-ga-nuong-mat-ong.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 5,
                            FoodName = "Đùi gà nướng",
                            Image_Url = "https://cdn.tgdd.vn/2020/06/CookProduct/21-1200x676-1.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 6,
                            FoodName = "Cá basa nướng",
                            Image_Url = "https://www.licious.in/blog/wp-content/uploads/2020/12/Grilled-Fish.jpg",
                            Type = "meat"
                        },
                        new
                        {
                            FoodId = 7,
                            FoodName = "Salad trộn",
                            Image_Url = "https://www.zimbokitchen.com/wp-content/uploads/2020/07/GREEN-SALAD-II.jpg",
                            Type = "vegetable"
                        },
                        new
                        {
                            FoodId = 8,
                            FoodName = "Bắp mỹ",
                            Image_Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmEH8Xu8lA_wB4SkdUTDARrjo0SqNJOQAKxVtc7youqw&s",
                            Type = "vegetable"
                        },
                        new
                        {
                            FoodId = 9,
                            FoodName = "Củ cải vàng muối",
                            Image_Url = "https://wikianngon.com/wp-content/uploads/2020/09/cu-cai-vang-muoi-1.jpg",
                            Type = "vegetable"
                        },
                        new
                        {
                            FoodId = 10,
                            FoodName = "Kim chi",
                            Image_Url = "https://www.huongnghiepaau.com/wp-content/uploads/2022/06/kim-chi-cai-thao-chua-vi-han-quoc.jpg",
                            Type = "vegetable"
                        },
                        new
                        {
                            FoodId = 11,
                            FoodName = "Onigiri",
                            Image_Url = "https://www.onigiri.casa/static/8fd936b83d13a9eed5b0cbe6346beccd/5d415/onigiri-salmon.jpg",
                            Type = "rice"
                        },
                        new
                        {
                            FoodId = 12,
                            FoodName = "Tteokbokki",
                            Image_Url = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Tteokbokki.JPG/640px-Tteokbokki.JPG",
                            Type = "rice"
                        },
                        new
                        {
                            FoodId = 13,
                            FoodName = "Kimbap",
                            Image_Url = "https://nhatkycuacoay.com/wp-content/uploads/2022/05/huong-dan-lam-com-cuon-rong-bien7.webp",
                            Type = "rice"
                        },
                        new
                        {
                            FoodId = 14,
                            FoodName = "Khoai tây chiên",
                            Image_Url = "https://www.recipetineats.com/wp-content/uploads/2022/09/Fries-with-rosemary-salt_1.jpg",
                            Type = "snack"
                        },
                        new
                        {
                            FoodId = 15,
                            FoodName = "Khoai lang lắc",
                            Image_Url = "https://www.ilovelindsay.com/assets/components/phpthumbof/cache/yukonsweetpotatoes_small.f82724c758f5a7e1142cf0568b85d580.jpg",
                            Type = "snack"
                        },
                        new
                        {
                            FoodId = 16,
                            FoodName = "Dưa hấu",
                            Image_Url = "https://hips.hearstapps.com/hmg-prod/images/fresh-ripe-watermelon-slices-on-wooden-table-royalty-free-image-1684966820.jpg?crop=0.88973xw:1xh;center,top&resize=1200:*",
                            Type = "dessert"
                        },
                        new
                        {
                            FoodId = 17,
                            FoodName = "Ổi",
                            Image_Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnacAyYre-T-SiLPfe3zc_XQPuymPU2ZNpJjTAiUTXSA&s",
                            Type = "dessert"
                        });
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.FoodIngredient", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Ingredient_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Use_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FoodId", "Ingredient_id");

                    b.HasIndex("Ingredient_id");

                    b.ToTable("FoodIngredients");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 1,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 1,
                            Ingredient_id = "TB",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 2,
                            Ingredient_id = "BC",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 2,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 2,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 3,
                            Ingredient_id = "CG1",
                            Unit = "cái",
                            Use_quantity = 2.00m
                        },
                        new
                        {
                            FoodId = 3,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 3,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 4,
                            Ingredient_id = "CG2",
                            Unit = "cái",
                            Use_quantity = 2.00m
                        },
                        new
                        {
                            FoodId = 4,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 4,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 5,
                            Ingredient_id = "DG",
                            Unit = "cái",
                            Use_quantity = 2.00m
                        },
                        new
                        {
                            FoodId = 5,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 5,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 6,
                            Ingredient_id = "CBS",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 6,
                            Ingredient_id = "GU",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 6,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.01m
                        },
                        new
                        {
                            FoodId = 7,
                            Ingredient_id = "CC",
                            Unit = "quả",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 7,
                            Ingredient_id = "DL",
                            Unit = "quả",
                            Use_quantity = 0.50m
                        },
                        new
                        {
                            FoodId = 7,
                            Ingredient_id = "EGG",
                            Unit = "quả",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 7,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 7,
                            Ingredient_id = "SL",
                            Unit = "kg",
                            Use_quantity = 0.20m
                        },
                        new
                        {
                            FoodId = 8,
                            Ingredient_id = "CORN",
                            Unit = "quả",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 9,
                            Ingredient_id = "CCV",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 9,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 10,
                            Ingredient_id = "CT",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 10,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 11,
                            Ingredient_id = "CBS",
                            Unit = "kg",
                            Use_quantity = 0.03m
                        },
                        new
                        {
                            FoodId = 11,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 11,
                            Ingredient_id = "RB",
                            Unit = "lát",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 11,
                            Ingredient_id = "RICE",
                            Unit = "kg",
                            Use_quantity = 0.10m
                        },
                        new
                        {
                            FoodId = 12,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 12,
                            Ingredient_id = "TOK",
                            Unit = "kg",
                            Use_quantity = 0.30m
                        },
                        new
                        {
                            FoodId = 13,
                            Ingredient_id = "DL",
                            Unit = "quả",
                            Use_quantity = 0.50m
                        },
                        new
                        {
                            FoodId = 13,
                            Ingredient_id = "EGG",
                            Unit = "quả",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 13,
                            Ingredient_id = "RB",
                            Unit = "lát",
                            Use_quantity = 5.00m
                        },
                        new
                        {
                            FoodId = 13,
                            Ingredient_id = "RICE",
                            Unit = "kg",
                            Use_quantity = 0.50m
                        },
                        new
                        {
                            FoodId = 13,
                            Ingredient_id = "SS",
                            Unit = "cây",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 14,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 14,
                            Ingredient_id = "KT",
                            Unit = "củ",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 15,
                            Ingredient_id = "GV",
                            Unit = "gói",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 15,
                            Ingredient_id = "KL",
                            Unit = "củ",
                            Use_quantity = 1.00m
                        },
                        new
                        {
                            FoodId = 16,
                            Ingredient_id = "DH",
                            Unit = "kg",
                            Use_quantity = 0.50m
                        },
                        new
                        {
                            FoodId = 17,
                            Ingredient_id = "OI",
                            Unit = "quả",
                            Use_quantity = 1.00m
                        });
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Ingredient", b =>
                {
                    b.Property<string>("Ingredient_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ingredient_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Order_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stored_quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ingredient_id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Ingredient_id = "BC",
                            Ingredient_name = "Ba chỉ",
                            Order_quantity = 10.00m,
                            Stored_quantity = 14.10m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "CBS",
                            Ingredient_name = "Cá basa",
                            Order_quantity = 10.00m,
                            Stored_quantity = 14.87m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "CC",
                            Ingredient_name = "Cà chua",
                            Order_quantity = 40.00m,
                            Stored_quantity = 47.00m,
                            Unit = "quả"
                        },
                        new
                        {
                            Ingredient_id = "CCV",
                            Ingredient_name = "Củ cải vàng",
                            Order_quantity = 10.00m,
                            Stored_quantity = 19.90m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "CG1",
                            Ingredient_name = "Cánh gà",
                            Order_quantity = 100.00m,
                            Stored_quantity = 104.00m,
                            Unit = "cái"
                        },
                        new
                        {
                            Ingredient_id = "CG2",
                            Ingredient_name = "Chân gà",
                            Order_quantity = 100.00m,
                            Stored_quantity = 106.00m,
                            Unit = "cái"
                        },
                        new
                        {
                            Ingredient_id = "CORN",
                            Ingredient_name = "Bắp mỹ",
                            Order_quantity = 40.00m,
                            Stored_quantity = 44.00m,
                            Unit = "quả"
                        },
                        new
                        {
                            Ingredient_id = "CT",
                            Ingredient_name = "Cải thảo",
                            Order_quantity = 10.00m,
                            Stored_quantity = 19.90m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "DG",
                            Ingredient_name = "Đùi gà",
                            Order_quantity = 100.00m,
                            Stored_quantity = 108.00m,
                            Unit = "cái"
                        },
                        new
                        {
                            Ingredient_id = "DH",
                            Ingredient_name = "Dưa hấu",
                            Order_quantity = 10.00m,
                            Stored_quantity = 20.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "DL",
                            Ingredient_name = "Dưa leo",
                            Order_quantity = 40.00m,
                            Stored_quantity = 48.00m,
                            Unit = "quả"
                        },
                        new
                        {
                            Ingredient_id = "EGG",
                            Ingredient_name = "Trứng",
                            Order_quantity = 40.00m,
                            Stored_quantity = 46.00m,
                            Unit = "quả"
                        },
                        new
                        {
                            Ingredient_id = "GU",
                            Ingredient_name = "Gói ướp",
                            Order_quantity = 90.00m,
                            Stored_quantity = 78.00m,
                            Unit = "gói"
                        },
                        new
                        {
                            Ingredient_id = "GV",
                            Ingredient_name = "Gói gia vị",
                            Order_quantity = 90.00m,
                            Stored_quantity = 93.00m,
                            Unit = "gói"
                        },
                        new
                        {
                            Ingredient_id = "KL",
                            Ingredient_name = "Khoai lang",
                            Order_quantity = 40.00m,
                            Stored_quantity = 50.00m,
                            Unit = "củ"
                        },
                        new
                        {
                            Ingredient_id = "KT",
                            Ingredient_name = "Khoai tây",
                            Order_quantity = 40.00m,
                            Stored_quantity = 50.00m,
                            Unit = "củ"
                        },
                        new
                        {
                            Ingredient_id = "OI",
                            Ingredient_name = "Ổi",
                            Order_quantity = 10.00m,
                            Stored_quantity = 7.00m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "RB",
                            Ingredient_name = "Rong biển",
                            Order_quantity = 50.00m,
                            Stored_quantity = 54.00m,
                            Unit = "lát"
                        },
                        new
                        {
                            Ingredient_id = "RICE",
                            Ingredient_name = "Cơm",
                            Order_quantity = 10.00m,
                            Stored_quantity = 19.40m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "SL",
                            Ingredient_name = "Salad",
                            Order_quantity = 20.00m,
                            Stored_quantity = 29.18m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "SS",
                            Ingredient_name = "Xúc xích",
                            Order_quantity = 40.00m,
                            Stored_quantity = 49.00m,
                            Unit = "cây"
                        },
                        new
                        {
                            Ingredient_id = "TB",
                            Ingredient_name = "Thăn bò",
                            Order_quantity = 10.00m,
                            Stored_quantity = 14.40m,
                            Unit = "kg"
                        },
                        new
                        {
                            Ingredient_id = "TOK",
                            Ingredient_name = "Tteokbokki",
                            Order_quantity = 20.00m,
                            Stored_quantity = 29.70m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Menu", b =>
                {
                    b.Property<DateTime>("TimeOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("TimeOrder", "OrderId");

                    b.HasIndex("FoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Orders", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IsUsed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatingId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("SeatingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$11$cskKWDv1XVOxT8Bv/lukL.NdjnxkgOCPw.oNNfDhkA4iMGC6kXiVO",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$11$EsEyeaTLMfOTNIlnk.2cguP0n5Nryn7zdupVTeJI7/MqZVvovuyju",
                            Username = "Anh"
                        },
                        new
                        {
                            Id = 3,
                            Password = "$2a$11$6kOi/z0O6tViDKp8.qmtw.bxksF2M1nt/W7nmqH.8ft09FBVc8t26",
                            Username = "Bac"
                        },
                        new
                        {
                            Id = 4,
                            Password = "$2a$11$C86ljVQ5t5amPuF59o1QweQWNoaYiv8DleHV6DOE2BeH.97CP2.OC",
                            Username = "Nhi"
                        });
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Table", b =>
                {
                    b.Property<int>("SeatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatingId"));

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatingId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            SeatingId = 1,
                            Status = "waiting"
                        },
                        new
                        {
                            SeatingId = 2,
                            Status = "waiting"
                        },
                        new
                        {
                            SeatingId = 3,
                            Status = "waiting"
                        },
                        new
                        {
                            SeatingId = 4,
                            Status = "waiting"
                        },
                        new
                        {
                            SeatingId = 5,
                            Status = "waiting"
                        });
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Bill", b =>
                {
                    b.HasOne("NhaHangBuffetPBL3.Models.Table", "table")
                        .WithMany()
                        .HasForeignKey("SeatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("table");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.FoodIngredient", b =>
                {
                    b.HasOne("NhaHangBuffetPBL3.Models.Food", "Food")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaHangBuffetPBL3.Models.Ingredient", "Ingredient")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Menu", b =>
                {
                    b.HasOne("NhaHangBuffetPBL3.Models.Food", "Food")
                        .WithMany("Menus")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaHangBuffetPBL3.Models.Orders", "Order")
                        .WithMany("menu")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Orders", b =>
                {
                    b.HasOne("NhaHangBuffetPBL3.Models.Table", "Table")
                        .WithMany("orders")
                        .HasForeignKey("SeatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Food", b =>
                {
                    b.Navigation("FoodIngredients");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Ingredient", b =>
                {
                    b.Navigation("FoodIngredients");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Orders", b =>
                {
                    b.Navigation("menu");
                });

            modelBuilder.Entity("NhaHangBuffetPBL3.Models.Table", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
